/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as InteriorSpacesRouteImport } from './routes/interior-spaces'
import { Route as HodchStoreRouteImport } from './routes/hodch-store'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'

const InteriorSpacesRoute = InteriorSpacesRouteImport.update({
  id: '/interior-spaces',
  path: '/interior-spaces',
  getParentRoute: () => rootRouteImport,
} as any)
const HodchStoreRoute = HodchStoreRouteImport.update({
  id: '/hodch-store',
  path: '/hodch-store',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/hodch-store': typeof HodchStoreRoute
  '/interior-spaces': typeof InteriorSpacesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/hodch-store': typeof HodchStoreRoute
  '/interior-spaces': typeof InteriorSpacesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/hodch-store': typeof HodchStoreRoute
  '/interior-spaces': typeof InteriorSpacesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/hodch-store' | '/interior-spaces'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/hodch-store' | '/interior-spaces'
  id: '__root__' | '/' | '/auth' | '/hodch-store' | '/interior-spaces'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  HodchStoreRoute: typeof HodchStoreRoute
  InteriorSpacesRoute: typeof InteriorSpacesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/interior-spaces': {
      id: '/interior-spaces'
      path: '/interior-spaces'
      fullPath: '/interior-spaces'
      preLoaderRoute: typeof InteriorSpacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hodch-store': {
      id: '/hodch-store'
      path: '/hodch-store'
      fullPath: '/hodch-store'
      preLoaderRoute: typeof HodchStoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  HodchStoreRoute: HodchStoreRoute,
  InteriorSpacesRoute: InteriorSpacesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
